### ISSUE TITLE
Workflow script

### ISSUE THREAD

**Issue by tkswanson** [conservationtechlab/animl-py#14]
Add a main script that runs the entire workflow start to finish, given an image directory and model locations
The script should contain debugging statements for testing that can be muted by advanced users when used for real analysis

**Comment by srinidhi98** [comment]
Pushed the main workflow : main_imageproc.py(renamed it to meet snakecase standards but can rename it again). It works and has been linted. Contains docstrings and debugging statements. Args are given through command line.
